### ISSUE TITLE
Edit Registration page

### ISSUE THREAD

**Issue by MarwanSdeek** [MarwanSdeek/ISC-Egypt#3]
Add Registration to Headr Nav. bar

**Comment by MarwanSdeek** [comment]
-- Add to sent msg "Thanks For Registration in ISC - Egypt '15 "
-- Remove Track
-- Add Auto generated ID and send to Submitter.
-- Clarification msg about usage of ID ( This ID will be used during fees payment ).

**Comment by MarwanSdeek** [comment]
Add "Sent ID will be used during fees payment" to registration-confirmation

**Comment by EmanAyman** [comment]
For Registeration page, add a droplist menu below the name textbox directly to choose from author or attendee

add phone number to the list and make it necessary
