### ISSUE TITLE
for the website title

### ISSUE THREAD

**Issue by EmanAyman** [MarwanSdeek/ISC-Egypt#34]
remove Egypt add Cairo university 

Replace
ISC – Egypt '15
2nd IEEE EMBS International Students Conference ( Egypt, 15- 17 October, 2015)

with
ISC – Egypt '15
2nd IEEE EMBS International Students Conference ( Cairo University, Egypt, 15- 17 October, 2015)

**Comment by MarwanSdeek** [comment]
Plz check it now

**Comment by EmanAyman** [comment]
Tamam
