### ISSUE TITLE
papers & projects -->project submission tab

### ISSUE THREAD

**Issue by EmanAyman** [MarwanSdeek/ISC-Egypt#43]
3ayzen n3mel nafs el submission bta3 el papers

hanshel submit paper  w nektb ---> submit project

w nafs el data hanshel bas track w nkteb  --> project title

w hanshel paper  w nektb project abstract  

w nafs el process w kol 7aga :)

**Comment by MarwanSdeek** [comment]
new mail for projects 
projects@iscegypt.org

Please test it and paper submission form

**Comment by EmanAyman** [comment]
tamaam :)
password el mail eh ??  Eman A. Hassan
.......................................................Teaching & Research Assistant Systems & Biomedical  DepartmentFaculty Of EngineeringCairo University
Giza 12613, Egypt

  

```
 On Friday, August 21, 2015 2:12 PM, MarwanSdeek <notifications@github.com> wrote:
```

 new mail for projects 
projects@iscegypt.orgPlease test it and paper submission form —
