### ISSUE TITLE
program -- > challenges and start ups

### ISSUE THREAD

**Issue by EmanAyman** [MarwanSdeek/ISC-Egypt#52]
Talk 1
Title: "Sadeem" challenges and future of Big Data on health care and Biomedical Engineering

![0982033](https://cloud.githubusercontent.com/assets/11407438/9706127/2e774ed0-54dc-11e5-8863-e1ac5f36a892.jpg)

Abstract
the talk will include:
- Big Data analysis field 
- Big Data application in Biomedical engineering and how to use it to improve the healthcare quality
- Sadeem as a startup in this field 
- Challenges faced and still facing Sadeem

Biography
- 15 years Experiences in Software Industry
- Chief Technology Officer for Two Enterprise Companies
- International company Assessment Consultant 
- Semantic Web & Big Data Analytics Researcher in Juan Rey Carlos , Madrid, Spain
- Scientific & Technical adviser  in ANSR lab , Cairo University
- Big Data Implementation Consultant
- Internet of Things Forum Member

**Comment by MarwanSdeek** [comment]
Men b2a :D !!
