### ISSUE TITLE
urgent urgent 

### ISSUE THREAD

**Issue by EmanAyman** [MarwanSdeek/ISC-Egypt#55]
3ayzen mail ll registration ma3lesh rag3o ba2a tany

w 3ayzen el list elly etb3tet bel registration w updates kol shwaya tetb3et 3ala mail el registration

**Comment by MarwanSdeek** [comment]
It's never been deleted 
registration@iscegypt.org
Pass: same criteria for other mails  
-- updates are continuously sent to it ( last update 20/9/2015 at 2.03 am
